menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/longweiquan
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: longweiquan
#duoshuo:

# Analytics
# google-analytics:
ga: UA-63462717-1

# Copyright Infomation
startyear: 2015
